name: Companion Module Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Check module
    permissions:
      contents: read
      packages: read
    uses: bitfocus/actions/.github/workflows/module-checks.yaml@main
    with:
      upload-artifact: true
